# Generated by Django 2.1.2 on 2018-12-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=5)),
                ('securitycode', models.CharField(max_length=3)),
                ('nameofcardholder', models.CharField(max_length=245)),
                ('expirydate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RechargeCardM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('code', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
