# Generated by Django 2.1.2 on 2018-12-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargecardm',
            name='price',
            field=models.DecimalField(choices=[(1, 100), (2, 200), (3, 500), (4, 100)], decimal_places=2, max_digits=5),
        ),
    ]
