# Generated by Django 2.1.2 on 2018-12-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181223_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargecardm',
            name='name',
            field=models.CharField(choices=[(1, 'MTN'), (2, 'GLO'), (3, 'Etisalat'), (4, 'Airtel')], max_length=245),
        ),
    ]
