# Generated by Django 2.1.2 on 2018-12-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20181223_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardm',
            name='cardnumber',
            field=models.CharField(max_length=10, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='creditcardm',
            name='expirydate',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='creditcardm',
            name='nameofcardholder',
            field=models.CharField(max_length=245, verbose_name='Name Of Cardholder'),
        ),
        migrations.AlterField(
            model_name='creditcardm',
            name='securitycode',
            field=models.CharField(max_length=3, verbose_name='Security Code'),
        ),
        migrations.AlterField(
            model_name='creditcardm',
            name='zipcode',
            field=models.CharField(max_length=5, verbose_name='Zipcode'),
        ),
    ]
